# Generated by Django 3.1.1 on 2020-10-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20200930_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
