# Generated by Django 3.1.2 on 2020-11-05 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='connection',
        ),
    ]
